services:
  api:
    build:
      context: ./ 
      dockerfile: docker/api/Dockerfile
    command: uvicorn api.main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - ./src:/code 
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "8000:8000"
    env_file:
      - ./.env.dev 

  python_runner:
    build:
      context: ./
      dockerfile: docker/code_runner/Dockerfile
    volumes:
      - code_execution_volume:/code
    command: ["tail", "-f", "/dev/null"] 
    pids_limit: 10
    security_opt:
      - no-new-privileges:true

volumes:
  code_execution_volume: