services:
  api:
    build:
      context: ./ 
      dockerfile: docker/api/Dockerfile
    command: uvicorn api.main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - ./src:/code 
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "8000:8000"

  python_runner:
    container_name: agentrun-api-python-runner-1
    build:
      context: ./
      dockerfile: docker/code_runner/Dockerfile
    volumes:
      - code_execution_volume:/code
    command: ["tail", "-f", "/dev/null"] 
    pids_limit: 10
    security_opt:
      - no-new-privileges:true
    environment:
      - OPENBLAS_NUM_THREADS=1 # this specifically for a numpy bug. See: https://github.com/Jonathan-Adly/AgentRun/issues/7#issue-2306842471
volumes:
  code_execution_volume: